base/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path ('',include('feed.urls')),
    
    # everything that is not a function 
    path('users/',include('users.urls')),

]

feed/urls.py
# this is the feed url 
#IDNETICAL 

import inspect
from django.urls import *

from .views import *



app_name= 'feed'


urlpatterns = [
   
    


# this is the detail page of the view that also includes the comment form 
    path('inspect/<int:id>',Detail , name='inspect'),  # maybe its caling this one instead of 22 

    path('like/<int:id>', like_post ,name='like-post'),

    # add to favorites function 
    path('fav/<int:id>', add_to_fav ,name='favorite_add'),

    # view the added to favorite 
    path('fav_list/', fav_list ,name='favorite_list'),

    path('',feedpage_view.as_view(),name='first'),

    path('inspect/<int:id>/comment/', Add_comment_class.as_view(),name='add_commento'),


    path('more/',more_view.as_view(),name='more'),
]
 

functions/models.py
from django.db import models

# Create your models here.

functions/views.py
from django.shortcuts import render

# Create your views here.

functions/templates/functions/comment_navbar.html
<!DOCTYPE html>
<html>
<head>
<style>
ul {
    list-style-type: none;
    margin: 0;
    padding: 0;
    overflow: hidden;
    background-color: #333;
}

li {
    float: left;
}

li a {
    display: block;
    color: white;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
}

li a:hover {
    background-color: #111;
}
</style>
</head>
<body>

<ul>
    <!-- there has to be a for loop for the comment to work -->
    <!-- post , form -->
    

 
  <li><a class="active" href="{% url 'feed:first' %}">Return</a></li>
  <!-- this needs an id - its the same navbar that shows up on every post - t-->

  <li><a class="active" href=""> + Comment </a></li> <!-- this needs an id  -->
    <!-- what goes before the .id -->

  <li><a class="active" href=""> + save </a></li>

 
 

</ul>




</body>
{% block content %} 
{% endblock %}
</html>

functions/templates/functions/more_navbar.html
<!DOCTYPE html>
<html>
<head>
<style>
ul {
    list-style-type: none;
    margin: 0;
    padding: 0;
    overflow: hidden;
    background-color: #333;
}

li {
    float: left;
}

li a {
    display: block;
    color: white;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
}

li a:hover {
    background-color: #111;
}
</style>
</head>
<body>

<ul>

    {% if user.is_authenticated %}

                   
    <li><a class="active" href="{% url 'feed:first' %}">Return</a></li>
 
  <li><a href="">profile </a></li>
  <li><a href="">upgrade </a></li>
                    {% else %}


      <li><a class="active" href="{% url 'login' %}">Login</a></li>
      <li><a href="{% url 'feed:first' %}">Article's</a></li>
  <li><a href="">Favorites</a></li>
  <li><a href="{% url 'feed:more' %}">More</a></li>                 
                    {% endif %}
 
</ul>

</body>
{% block content %} 
{% endblock %}
</html>

functions/templates/functions/navbar.html
<!DOCTYPE html>
<html>
<head>
<style>
ul {
    list-style-type: none;
    margin: 0;
    padding: 0;
    overflow: hidden;
    background-color: #333;
}

li {
    float: left;
}

li a {
    display: block;
    color: white;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
}

li a:hover {
    background-color: #111;
}
</style>
</head>
<body>

<ul>

    {% if user.is_authenticated %}

                   
    <li><a class="active" href="{% url 'logout' %}">Logout</a></li>
  <li><a href="{% url 'feed:first' %}">Article's</a></li>
  <li><a href="{% url 'feed:favorite_list' %}">saved list </a></li>
  <li><a href="">More</a></li>
                    {% else %}


      <li><a class="active" href="{% url 'login' %}">Login</a></li>
      <li><a href="{% url 'feed:first' %}">Article's</a></li>
  <li><a href="">Favorites</a></li>
  <li><a href="">More</a></li>                 
                    {% endif %}
 
</ul>

</body>
{% block content %} 
{% endblock %}
</html>